---
- name: install and configure nginx
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    nginx_user: www-data
    nginx_worker_processes: auto
    nginx_server_name: example.com
    nginx_worker_connections: 1024
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: apply template
      template: 
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: check started nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: check conn port 80
      wait_for:
        port: 80
        host: "{{ nginx_server_name }}"
        timeout: 10
      delegate_to: localhost 

    - name: check conn port 443
      wait_for:
        port: 443
        host: "{{ nginx_server_name }}"
        timeout: 10
      delegate_to: localhost 

  handlers: 
    - name: restart nginx
      service:
        name: nginx
        state: restarted

