FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf

COPY html/example.html /usr/share/nginx/html/example.html
COPY source/nginx.conf /etc/nginx/conf.d/default.conf
COPY certs/cert.pem /etc/ssl/certs/cert.pem
COPY certs/key.pem /etc/ssl/private/key.pem

EXPOSE 80
EXPOSE 443
